RETRIEVAL_METHODS:
- CAMP

MATCHING_METHODS:
 - Roma
#   - SP_LG
#   - SP_LG_GIM
#   - SP_LG_MINIMA
#  - ALIKED_LG
#   - DISK_LG


PNP_METHODS:
- P3P

RETRIEVAL_COVER: 50
RETRIEVAL_TOPN: 5
RETRIEVAL_IMG: /1_Retrieval.jpg
RETRIEVAL_IMG_NUM: 5
RETRIEVAL_FEATURE_NORM: true
BATCH_SIZE: 128
